spring:
   application:
        name:
           department-service
   config:
        import:
           configserver:http://localhost:8888
management:
   endpoints:
        web:
           exposure:
               include:*
